
spring:
  security:
    oauth2:
      client:
        registration:
          clientapp:
            client-id: clientapp
            client-secret: 1234
#            isValidRedirectUri
#            http://127.0.0.1:8080/oauth2/authorization/felord
#todo        redirect-uri:  '{baseUrl}/foo/bar' 错误的写法  根据oauth2协议localhost不可被解析
#            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
#            redirect-uri:  'http://127.0.0.1:9050/foo/bar'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: message.read,message.write,openid,profile
        provider:
          clientapp:
#todo       provider 尽量用域名  不要用localhost或者IP  而且要和well-known接口中保持一致
            issuer-uri: http://localhost:9050
#           issuer-uri 可以简化下面的配置
#            authorization-uri: http://localhost:9000/oauth2/authorize
#            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9050/userDetails
            user-name-attribute: username
#            user-info-authentication-method: GET

# 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
server:
  port: 9051
  servlet:
    session:
      cookie:
        name: client2