
spring:
  security:
    oauth2:
#      client:
#        registration:
#          clientapp:
#            client-id: clientapp
#            client-secret: 1234
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9050
          jwk-set-uri: http://localhost:9050/oauth2/jwks
#        opaquetoken:
#          client-id: clientapp
#          client-secret: 1234


# 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
server:
  port: 9052
  servlet:
    session:
      cookie:
        name: resource