spring:
  application:
    name: authorization-server
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
server:
  port: 9050
  servlet:
    session:
      cookie:
        name: server2
# 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

#  keytool.exe -genkeypair -alias oauthJwt -keyalg RSA -keypass 123456  -storepass 111111  -keyalg RSA -keysize 2048  -validity 3650  -keystore oauthJwt.jks