spring:
  security:
    oauth2:
      client:
        registration:
          clientapp:
            client-id: clientapp
            client-secret: 1234
#            isValidRedirectUri
#            http://127.0.0.1:8080/oauth2/authorization/felord
#todo        redirect-uri:  '{baseUrl}/foo/bar' 错误的写法  根据oauth2协议localhost不可被解析
#            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            redirect-uri:  'http://127.0.0.1:8080/login/oauth2/code/clientapp'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: read_user_info
        provider:
          clientapp:
#todo       provider 尽量用域名  不要用localhost或者IP  而且要和well-known接口中保持一致
#            issuer-uri: http://localhost:9000
#           issuer-uri 可以简化下面的配置
            authorization-uri: http://localhost:9000/oauth/authorize
            token-uri: http://localhost:9000/oauth/token
            user-info-uri: http://localhost:9000/api/users/me # http://your-userinfo-endpoiont
            user-name-attribute: name
            user-info-authentication-method: QUERY  #  GET

# 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

server:
  servlet:
    session:
      cookie:
        name: client